# Generated by Django 4.2.3 on 2023-07-28 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_advertisements', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Advertisements',
            new_name='Advertisment',
        ),
        migrations.AlterModelTable(
            name='advertisment',
            table='advertisements',
        ),
    ]
